module.exports = {
  extends: "eslint:recommended",
  rules: {
    "arrow-body-style": 0,
    "max-len": 0,
    "no-plusplus": 0,
    "no-restricted-globals": 0,
    "no-return-await": 0,
    "no-underscore-dangle": 0,
    "no-use-before-define": 0,
    "no-void": 0,
    "no-alert": 1,
    "no-console": 1,
    "no-debugger": 1,
    "no-unused-vars": [
      1,
      {
        ignoreRestSiblings: true,
        argsIgnorePattern: "res|next|^err",
      },
    ],
    "accessor-pairs": 2,
    "array-callback-return": 2,
    "class-methods-use-this": 2,
    "consistent-return": 2,
    "default-case": 2,
    "default-case-last": 2,
    "default-param-last": 2,
    "dot-notation": 2,
    "func-names": 2,
    "guard-for-in": 2,
    "new-cap": 2,
    "no-array-constructor": 2,
    "no-async-promise-executor": 2,
    "no-await-in-loop": 2,
    "no-bitwise": 2,
    "no-caller": 2,
    "no-confusing-arrow": 2,
    "no-constructor-return": 2,
    "no-continue": 2,
    "no-div-regex": 2,
    "no-duplicate-imports": 2,
    "no-else-return": 2,
    "no-empty": 2,
    "no-empty-function": 2,
    "no-eval": 2,
    "no-extend-native": 2,
    "no-extra-bind": 2,
    "no-extra-label": 2,
    "no-floating-decimal": 2,
    "no-implicit-coercion": 2,
    "no-implied-eval": 2,
    "no-invalid-this": 2,
    "no-iterator": 2,
    "no-label-var": 2,
    "no-labels": 2,
    "no-lone-blocks": 2,
    "no-loop-func": 2,
    "no-magic-numbers": 2,
    "no-mixed-operators": 2,
    "no-multi-assign": 2,
    "no-multi-str": 2,
    "no-nested-ternary": 2,
    "no-new-object": 2,
    "no-new-wrappers": 2,
    "no-param-reassign": 2,
    "no-promise-executor-return": 2,
    "no-return-assign": [2, "except-parens"],
    "no-script-url": 2,
    "no-self-compare": 2,
    "no-sequences": 2,
    "no-template-curly-in-string": 2,
    "no-throw-literal": 2,
    "no-undefined": 2,
    "no-unmodified-loop-condition": 2,
    "no-unneeded-ternary": 2,
    "no-unreachable-loop": 2,
    "no-unused-expressions": 2,
    "no-unused-private-class-members": 2,
    "no-useless-call": 2,
    "no-useless-computed-key": 2,
    "no-useless-concat": 2,
    "no-useless-constructor": 2,
    "no-useless-rename": 2,
    "no-useless-return": 2,
    "no-var": 2,
    "object-shorthand": 2,
    "one-var-declaration-per-line": 2,
    "operator-assignment": 2,
    "prefer-const": 2,
    "prefer-destructuring": 2,
    "prefer-exponentiation-operator": 2,
    "prefer-named-capture-group": 2,
    "prefer-object-has-own": 2,
    "prefer-object-spread": 2,
    "prefer-promise-reject-errors": 2,
    "prefer-regex-literals": 2,
    "prefer-rest-params": 2,
    "prefer-spread": 2,
    "prefer-template": 2,
    "quote-props": 2,
    "require-atomic-updates": 2,
    "require-await": 2,
    "require-unicode-regexp": 2,
    "space-before-function-paren": [2, "always"],
    "spaced-comment": 2,
    camelcase: 2,
    curly: 2,
    radix: 2,
    strict: 2,
    yoda: 2,
    "no-restricted-syntax": [
      2,
      "ForInStatement",
      "DoWhileStatement",
      "LabeledStatement",
      "WithStatement",
    ],
    "no-unused-expressions": [
      2,
      {
        allowTaggedTemplates: true,
      },
    ],
    "no-shadow": [
      2,
      {
        hoist: "all",
        allow: ["resolve", "reject", "done", "next", "err", "error"],
      },
    ],
  },
};
